# make kitty have no extra stuff. just a floating terminal
draw_minimal_borders yes
allow_remote_control yes

# theme
# to change theme, use 
# rm ~/.config/kitty/theme.conf && ln -s ./kitty-themes/themes/<THEME_OF_CHOICE>.conf ~/.config/kitty/theme.conf
# to replace the symbolic link for the old theme with the new one
include ./theme.conf

# font
font_family JetBrainsMono Nerd Font Mono
font_size 8.75

# default window size
remember_window_size no
initial_window_width 1100
initial_window_height 600

# other behavior
copy_on_select yes
mouse_selection_clipboard yes
mouse_map ctrl+shift+right press ungrabbeleft d mouse_selection rectangle

# ctrl+shift+hjkl up/down/left/right
map ctrl+k send_text all \x1b[A
map ctrl+j send_text all \x1b[B
map ctrl+h send_text all \x1b[D
map ctrl+l send_text all \x1b[C

# alt+shift+h/l move left/right by a word
map alt+shift+h send_key ctrl+left
map alt+shift+l send_key ctrl+right

# kitty tab actions
map ctrl+shift+h previous_tab
map ctrl+shift+l next_tab
map alt+shift+- launch --location=hsplit
map alt+shift+\ launch --location=vsplit 
enabled_layouts splits
map ctrl+shift+1 goto_tab 1
map ctrl+shift+2 goto_tab 2
map ctrl+shift+3 goto_tab 3
map ctrl+shift+4 goto_tab 4
map ctrl+shift+5 goto_tab 5
map ctrl+shift+6 goto_tab 6
map ctrl+shift+7 goto_tab 7
map ctrl+shift+9 goto_tab 9
map ctrl+shift+10 goto_tab 10
# to rename a tab it's ctrl+shift+alt+t

# tab bar customization
tab_bar_edge top
tab_bar_style powerline
tab_powerline_style slanted
tab_title_template "{index}"
