general {
    lock_cmd = pidof hyprlock || hyprlock   # don't spawn multiple instances
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

listener {
    timeout = 300                          # 5 min → lock
    on-timeout = loginctl lock-session
}

listener {
    event = pwr_button  # This listens for the system power button event
    on-status-change = hyprlock
}

# listener {
#     timeout = 360                          # 6 min → screen off
#     on-timeout = hyprctl dispatch dpms off
#     on-resume = hyprctl dispatch dpms on
# }
#
# listener {
#     timeout = 1800                         # 30 min → suspend
#     on-timeout = systemctl suspend
# }
